package com.klinker.android.messaging_sliding.emojis;

import android.content.Context;
import android.graphics.Bitmap;
import android.graphics.BitmapFactory;
import android.graphics.Canvas;
import android.graphics.drawable.BitmapDrawable;
import android.graphics.drawable.Drawable;
import android.text.Spannable;
import android.text.Spannable.Factory;
import android.text.style.ImageSpan;
import android.util.TypedValue;
import com.klinker.android.messaging_donate.R;

import java.util.HashMap;
import java.util.Map;
import java.util.Map.Entry;
import java.util.regex.Matcher;
import java.util.regex.Pattern;

public class EmojiConverter {
    private static final Factory spannableFactory = Spannable.Factory
            .getInstance();

    private static final Map<Pattern, Integer> emoticons = new HashMap<Pattern, Integer>();

    static {
        addPattern(emoticons, "\ud83d\ude04", R.drawable.emoji_e415);
        addPattern(emoticons, "\ud83d\ude0a", R.drawable.emoji_e056);
        addPattern(emoticons, "\ud83d\ude03", R.drawable.emoji_e057);
        addPattern(emoticons, "\u263a", R.drawable.emoji_e414);
        addPattern(emoticons, "\ud83d\ude09", R.drawable.emoji_e405);
        addPattern(emoticons, "\ud83d\ude0d", R.drawable.emoji_e106);
        addPattern(emoticons, "\ud83d\ude18", R.drawable.emoji_e418);
        addPattern(emoticons, "\ud83d\ude1a", R.drawable.emoji_e417);
        addPattern(emoticons, "\ud83d\ude33", R.drawable.emoji_e40d);
        addPattern(emoticons, "\ud83d\ude0c", R.drawable.emoji_e40a);
        addPattern(emoticons, "\ud83d\ude01", R.drawable.emoji_e404);
        addPattern(emoticons, "\ud83d\ude1c", R.drawable.emoji_e105);
        addPattern(emoticons, "\ud83d\ude1d", R.drawable.emoji_e409);
        addPattern(emoticons, "\ud83d\ude12", R.drawable.emoji_e40e);
        addPattern(emoticons, "\ud83d\ude0f", R.drawable.emoji_e402);
        addPattern(emoticons, "\ud83d\ude13", R.drawable.emoji_e108);
        addPattern(emoticons, "\ud83d\ude14", R.drawable.emoji_e403);
        addPattern(emoticons, "\ud83d\ude1e", R.drawable.emoji_e058);
        addPattern(emoticons, "\ud83d\ude16", R.drawable.emoji_e407);
        addPattern(emoticons, "\ud83d\ude25", R.drawable.emoji_e401);
        addPattern(emoticons, "\ud83d\ude30", R.drawable.emoji_e40f);
        addPattern(emoticons, "\ud83d\ude28", R.drawable.emoji_e40b);
        addPattern(emoticons, "\ud83d\ude23", R.drawable.emoji_e406);
        addPattern(emoticons, "\ud83d\ude22", R.drawable.emoji_e413);
        addPattern(emoticons, "\ud83d\ude2d", R.drawable.emoji_e411);
        addPattern(emoticons, "\ud83d\ude02", R.drawable.emoji_e412);
        addPattern(emoticons, "\ud83d\ude32", R.drawable.emoji_e410);
        addPattern(emoticons, "\ud83d\ude31", R.drawable.emoji_e107);
        addPattern(emoticons, "\ud83d\ude20", R.drawable.emoji_e059);
        addPattern(emoticons, "\ud83d\ude21", R.drawable.emoji_e416);
        addPattern(emoticons, "\ud83d\ude2a", R.drawable.emoji_e408);
        addPattern(emoticons, "\ud83d\ude37", R.drawable.emoji_e40c);
        addPattern(emoticons, "\ud83d\udc7f", R.drawable.emoji_e11a);
        addPattern(emoticons, "\ud83d\udc7d", R.drawable.emoji_e10c);
        addPattern(emoticons, "\ud83d\udc9b", R.drawable.emoji_e32c);
        addPattern(emoticons, "\ud83d\udc99", R.drawable.emoji_e32a);
        addPattern(emoticons, "\ud83d\udc9c", R.drawable.emoji_e32d);
        addPattern(emoticons, "\ud83d\udc97", R.drawable.emoji_e328);
        addPattern(emoticons, "\ud83d\udc9a", R.drawable.emoji_e32b);
        addPattern(emoticons, "\u2764", R.drawable.emoji_e022);
        addPattern(emoticons, "\ud83d\udc94", R.drawable.emoji_e023);
        addPattern(emoticons, "\ud83d\udc93", R.drawable.emoji_e327);
        addPattern(emoticons, "\ud83d\udc98", R.drawable.emoji_e329);
        addPattern(emoticons, "\u2728", R.drawable.emoji_e32e);
        addPattern(emoticons, "\u2b50", R.drawable.emoji_e32f);
        addPattern(emoticons, "\ud83c\udf1f", R.drawable.emoji_e335);
        addPattern(emoticons, "\ud83d\udca2", R.drawable.emoji_e334);
        addPattern(emoticons, "\u2757", R.drawable.emoji_e021);
        addPattern(emoticons, "\u2755", R.drawable.emoji_e337);
        addPattern(emoticons, "\u2753", R.drawable.emoji_e020);
        addPattern(emoticons, "\u2754", R.drawable.emoji_e336);
        addPattern(emoticons, "\ud83d\udca4", R.drawable.emoji_e13c);
        addPattern(emoticons, "\ud83d\udca8", R.drawable.emoji_e330);
        addPattern(emoticons, "\ud83d\ude05", R.drawable.emoji_e331);
        addPattern(emoticons, "\ud83c\udfb6", R.drawable.emoji_e326);
        addPattern(emoticons, "\ud83c\udfb5", R.drawable.emoji_e03e);
        addPattern(emoticons, "\ud83d\udd25", R.drawable.emoji_e11d);
        addPattern(emoticons, "\ud83d\udca9", R.drawable.emoji_e05a);
        addPattern(emoticons, "\ud83d\udc4d", R.drawable.emoji_e00e);
        addPattern(emoticons, "\ud83d\udc4e", R.drawable.emoji_e421);
        addPattern(emoticons, "\ud83d\udc4c", R.drawable.emoji_e420);
        addPattern(emoticons, "\ud83d\udc4a", R.drawable.emoji_e00d);
        addPattern(emoticons, "\u270a", R.drawable.emoji_e010);
        addPattern(emoticons, "\u270c", R.drawable.emoji_e011);
        addPattern(emoticons, "\ud83d\udc4b", R.drawable.emoji_e41e);
        addPattern(emoticons, "\u270b", R.drawable.emoji_e012);
        addPattern(emoticons, "\ud83d\udc50", R.drawable.emoji_e422);
        addPattern(emoticons, "\ud83d\udc46", R.drawable.emoji_e22e);
        addPattern(emoticons, "\ud83d\udc47", R.drawable.emoji_e22f);
        addPattern(emoticons, "\ud83d\udc49", R.drawable.emoji_e231);
        addPattern(emoticons, "\ud83d\udc48", R.drawable.emoji_e230);
        addPattern(emoticons, "\ud83d\ude4c", R.drawable.emoji_e427);
        addPattern(emoticons, "\ud83d\ude4f", R.drawable.emoji_e41d);
        addPattern(emoticons, "\u261d", R.drawable.emoji_e00f);
        addPattern(emoticons, "\ud83d\udc4f", R.drawable.emoji_e41f);
        addPattern(emoticons, "\ud83d\udcaa", R.drawable.emoji_e14c);
        addPattern(emoticons, "\ud83d\udeb6", R.drawable.emoji_e201);
        addPattern(emoticons, "\ud83c\udfc3", R.drawable.emoji_e115);
        addPattern(emoticons, "\ud83d\udc6b", R.drawable.emoji_e428);
        addPattern(emoticons, "\ud83d\udc83", R.drawable.emoji_e51f);
        addPattern(emoticons, "\ud83d\udc6f", R.drawable.emoji_e429);
        addPattern(emoticons, "\ud83d\ude46", R.drawable.emoji_e424);
        addPattern(emoticons, "\ud83d\ude45", R.drawable.emoji_e423);
        addPattern(emoticons, "\ud83d\udc81", R.drawable.emoji_e253);
        addPattern(emoticons, "\ud83d\ude47", R.drawable.emoji_e426);
        addPattern(emoticons, "\ud83d\udc8f", R.drawable.emoji_e111);
        addPattern(emoticons, "\ud83d\udc91", R.drawable.emoji_e425);
        addPattern(emoticons, "\ud83d\udc86", R.drawable.emoji_e31e);
        addPattern(emoticons, "\ud83d\udc87", R.drawable.emoji_e31f);
        addPattern(emoticons, "\ud83d\udc85", R.drawable.emoji_e31d);
        addPattern(emoticons, "\ud83d\udc66", R.drawable.emoji_e001);
        addPattern(emoticons, "\ud83d\udc67", R.drawable.emoji_e002);
        addPattern(emoticons, "\ud83d\udc69", R.drawable.emoji_e005);
        addPattern(emoticons, "\ud83d\udc68", R.drawable.emoji_e004);
        addPattern(emoticons, "\ud83d\udc76", R.drawable.emoji_e51a);
        addPattern(emoticons, "\ud83d\udc75", R.drawable.emoji_e519);
        addPattern(emoticons, "\ud83d\udc74", R.drawable.emoji_e518);
        addPattern(emoticons, "\ud83d\udc71", R.drawable.emoji_e515);
        addPattern(emoticons, "\ud83d\udc72", R.drawable.emoji_e516);
        addPattern(emoticons, "\ud83d\udc73", R.drawable.emoji_e517);
        addPattern(emoticons, "\ud83d\udc77", R.drawable.emoji_e51b);
        addPattern(emoticons, "\ud83d\udc6e", R.drawable.emoji_e152);
        addPattern(emoticons, "\ud83d\udc7c", R.drawable.emoji_e04e);
        addPattern(emoticons, "\ud83d\udc78", R.drawable.emoji_e51c);
        addPattern(emoticons, "\ud83d\udc82", R.drawable.emoji_e51e);
        addPattern(emoticons, "\ud83d\udc80", R.drawable.emoji_e11c);
        addPattern(emoticons, "\ud83d\udc3e", R.drawable.emoji_e536);
        addPattern(emoticons, "\ud83d\udc8b", R.drawable.emoji_e003);
        addPattern(emoticons, "\ud83d\udc44", R.drawable.emoji_e41c);
        addPattern(emoticons, "\ud83d\udc42", R.drawable.emoji_e41b);
        addPattern(emoticons, "\ud83d\udc40", R.drawable.emoji_e419);
        addPattern(emoticons, "\ud83d\udc43", R.drawable.emoji_e41a);
        addPattern(emoticons, "\u2600", R.drawable.emoji_e04a);
        addPattern(emoticons, "\u2614", R.drawable.emoji_e04b);
        addPattern(emoticons, "\u2601", R.drawable.emoji_e049);
        addPattern(emoticons, "\u26c4", R.drawable.emoji_e048);
        addPattern(emoticons, "\ud83c\udf19", R.drawable.emoji_e04c);
        addPattern(emoticons, "\u26a1", R.drawable.emoji_e13d);
        addPattern(emoticons, "\ud83c\udf00", R.drawable.emoji_e443);
        addPattern(emoticons, "\ud83c\udf0a", R.drawable.emoji_e43e);
        addPattern(emoticons, "\ud83d\udc31", R.drawable.emoji_e04f);
        addPattern(emoticons, "\ud83d\udc36", R.drawable.emoji_e052);
        addPattern(emoticons, "\ud83d\udc2d", R.drawable.emoji_e053);
        addPattern(emoticons, "\ud83d\udc39", R.drawable.emoji_e524);
        addPattern(emoticons, "\ud83d\udc30", R.drawable.emoji_e52c);
        addPattern(emoticons, "\ud83d\udc3a", R.drawable.emoji_e52a);
        addPattern(emoticons, "\ud83d\udc38", R.drawable.emoji_e531);
        addPattern(emoticons, "\ud83d\udc2f", R.drawable.emoji_e050);
        addPattern(emoticons, "\ud83d\udc28", R.drawable.emoji_e527);
        addPattern(emoticons, "\ud83d\udc3b", R.drawable.emoji_e051);
        addPattern(emoticons, "\ud83d\udc37", R.drawable.emoji_e10b);
        addPattern(emoticons, "\ud83d\udc2e", R.drawable.emoji_e52b);
        addPattern(emoticons, "\ud83d\udc17", R.drawable.emoji_e52f);
        addPattern(emoticons, "\ud83d\udc12", R.drawable.emoji_e528);
        addPattern(emoticons, "\ud83d\udc34", R.drawable.emoji_e01a);
        addPattern(emoticons, "\ud83d\udc0e", R.drawable.emoji_e134);
        addPattern(emoticons, "\ud83d\udc2b", R.drawable.emoji_e530);
        addPattern(emoticons, "\ud83d\udc11", R.drawable.emoji_e529);
        addPattern(emoticons, "\ud83d\udc18", R.drawable.emoji_e526);
        addPattern(emoticons, "\ud83d\udc0d", R.drawable.emoji_e52d);
        addPattern(emoticons, "\ud83d\udc26", R.drawable.emoji_e521);
        addPattern(emoticons, "\ud83d\udc24", R.drawable.emoji_e523);
        addPattern(emoticons, "\ud83d\udc14", R.drawable.emoji_e52e);
        addPattern(emoticons, "\ud83d\udc27", R.drawable.emoji_e055);
        addPattern(emoticons, "\ud83d\udc1b", R.drawable.emoji_e525);
        addPattern(emoticons, "\ud83d\udc19", R.drawable.emoji_e10a);
        addPattern(emoticons, "\ud83d\udc35", R.drawable.emoji_e109);
        addPattern(emoticons, "\ud83d\udc20", R.drawable.emoji_e522);
        addPattern(emoticons, "\ud83d\udc1f", R.drawable.emoji_e019);
        addPattern(emoticons, "\ud83d\udc33", R.drawable.emoji_e054);
        addPattern(emoticons, "\ud83d\udc2c", R.drawable.emoji_e520);
        addPattern(emoticons, "\ud83d\udc90", R.drawable.emoji_e306);
        addPattern(emoticons, "\ud83c\udf38", R.drawable.emoji_e030);
        addPattern(emoticons, "\ud83c\udf37", R.drawable.emoji_e304);
        addPattern(emoticons, "\ud83c\udf40", R.drawable.emoji_e110);
        addPattern(emoticons, "\ud83c\udf39", R.drawable.emoji_e032);
        addPattern(emoticons, "\ud83c\udf3b", R.drawable.emoji_e305);
        addPattern(emoticons, "\ud83c\udf3a", R.drawable.emoji_e303);
        addPattern(emoticons, "\ud83c\udf41", R.drawable.emoji_e118);
        addPattern(emoticons, "\ud83c\udf43", R.drawable.emoji_e447);
        addPattern(emoticons, "\ud83c\udf42", R.drawable.emoji_e119);
        addPattern(emoticons, "\ud83c\udf34", R.drawable.emoji_e307);
        addPattern(emoticons, "\ud83c\udf35", R.drawable.emoji_e308);
        addPattern(emoticons, "\ud83c\udf3e", R.drawable.emoji_e444);
        addPattern(emoticons, "\ud83d\udc1a", R.drawable.emoji_e441);
        addPattern(emoticons, "\ud83c\udf8d", R.drawable.emoji_e436);
        addPattern(emoticons, "\ud83d\udc9d", R.drawable.emoji_e437);
        addPattern(emoticons, "\ud83c\udf8e", R.drawable.emoji_e438);
        addPattern(emoticons, "\ud83c\udf92", R.drawable.emoji_e43a);
        addPattern(emoticons, "\ud83c\udf93", R.drawable.emoji_e439);
        addPattern(emoticons, "\ud83c\udf8f", R.drawable.emoji_e43b);
        addPattern(emoticons, "\ud83c\udf86", R.drawable.emoji_e117);
        addPattern(emoticons, "\ud83c\udf87", R.drawable.emoji_e440);
        addPattern(emoticons, "\ud83c\udf90", R.drawable.emoji_e442);
        addPattern(emoticons, "\ud83c\udf91", R.drawable.emoji_e446);
        addPattern(emoticons, "\ud83c\udf83", R.drawable.emoji_e445);
        addPattern(emoticons, "\ud83d\udc7b", R.drawable.emoji_e11b);
        addPattern(emoticons, "\ud83c\udf85", R.drawable.emoji_e448);
        addPattern(emoticons, "\ud83c\udf84", R.drawable.emoji_e033);
        addPattern(emoticons, "\ud83c\udf81", R.drawable.emoji_e112);
        addPattern(emoticons, "\ud83d\udd14", R.drawable.emoji_e325);
        addPattern(emoticons, "\ud83c\udf89", R.drawable.emoji_e312);
        addPattern(emoticons, "\ud83c\udf88", R.drawable.emoji_e310);
        addPattern(emoticons, "\ud83d\udcbf", R.drawable.emoji_e126);
        addPattern(emoticons, "\ud83d\udcc0", R.drawable.emoji_e127);
        addPattern(emoticons, "\ud83d\udcf7", R.drawable.emoji_e008);
        addPattern(emoticons, "\ud83c\udfa5", R.drawable.emoji_e03d);
        addPattern(emoticons, "\ud83d\udcbb", R.drawable.emoji_e00c);
        addPattern(emoticons, "\ud83d\udcfa", R.drawable.emoji_e12a);
        addPattern(emoticons, "\ud83d\udcf1", R.drawable.emoji_e00a);
        addPattern(emoticons, "\ud83d\udce0", R.drawable.emoji_e00b);
        addPattern(emoticons, "\u260e", R.drawable.emoji_e009);
        addPattern(emoticons, "\ud83d\udcbd", R.drawable.emoji_e316);
        addPattern(emoticons, "\ud83d\udcfc", R.drawable.emoji_e129);
        addPattern(emoticons, "\ud83d\udd0a", R.drawable.emoji_e141);
        addPattern(emoticons, "\ud83d\udce2", R.drawable.emoji_e142);
        addPattern(emoticons, "\ud83d\udce3", R.drawable.emoji_e317);
        addPattern(emoticons, "\ud83d\udcfb", R.drawable.emoji_e128);
        addPattern(emoticons, "\ud83d\udce1", R.drawable.emoji_e14b);
        addPattern(emoticons, "\u27bf", R.drawable.emoji_e211);
        addPattern(emoticons, "\ud83d\udd0d", R.drawable.emoji_e114);
        addPattern(emoticons, "\ud83d\udd13", R.drawable.emoji_e145);
        addPattern(emoticons, "\ud83d\udd12", R.drawable.emoji_e144);
        addPattern(emoticons, "\ud83d\udd11", R.drawable.emoji_e03f);
        addPattern(emoticons, "\u2702", R.drawable.emoji_e313);
        addPattern(emoticons, "\ud83d\udd28", R.drawable.emoji_e116);
        addPattern(emoticons, "\ud83d\udca1", R.drawable.emoji_e10f);
        addPattern(emoticons, "\ud83d\udcf2", R.drawable.emoji_e104);
        addPattern(emoticons, "\ud83d\udce9", R.drawable.emoji_e103);
        addPattern(emoticons, "\ud83d\udceb", R.drawable.emoji_e101);
        addPattern(emoticons, "\ud83d\udcee", R.drawable.emoji_e102);
        addPattern(emoticons, "\ud83d\udec0", R.drawable.emoji_e13f);
        addPattern(emoticons, "\ud83d\udebd", R.drawable.emoji_e140);
        addPattern(emoticons, "\ud83d\udcba", R.drawable.emoji_e11f);
        addPattern(emoticons, "\ud83d\udcb0", R.drawable.emoji_e12f);
        addPattern(emoticons, "\ud83d\udd31", R.drawable.emoji_e031);
        addPattern(emoticons, "\ud83d\udeac", R.drawable.emoji_e30e);
        addPattern(emoticons, "\ud83d\udca3", R.drawable.emoji_e311);
        addPattern(emoticons, "\ud83d\udd2b", R.drawable.emoji_e113);
        addPattern(emoticons, "\ud83d\udc8a", R.drawable.emoji_e30f);
        addPattern(emoticons, "\ud83d\udc89", R.drawable.emoji_e13b);
        addPattern(emoticons, "\ud83c\udfc8", R.drawable.emoji_e42b);
        addPattern(emoticons, "\ud83c\udfc0", R.drawable.emoji_e42a);
        addPattern(emoticons, "\u26bd", R.drawable.emoji_e018);
        addPattern(emoticons, "\u26be", R.drawable.emoji_e016);
        addPattern(emoticons, "\ud83c\udfbe", R.drawable.emoji_e015);
        addPattern(emoticons, "\u26f3", R.drawable.emoji_e014);
        addPattern(emoticons, "\ud83c\udfb1", R.drawable.emoji_e42c);
        addPattern(emoticons, "\ud83c\udfca", R.drawable.emoji_e42d);
        addPattern(emoticons, "\ud83c\udfc4", R.drawable.emoji_e017);
        addPattern(emoticons, "\ud83c\udfbf", R.drawable.emoji_e013);
        addPattern(emoticons, "\u2660", R.drawable.emoji_e20e);
        addPattern(emoticons, "\u2665", R.drawable.emoji_e20c);
        addPattern(emoticons, "\u2663", R.drawable.emoji_e20f);
        addPattern(emoticons, "\u2666", R.drawable.emoji_e20d);
        addPattern(emoticons, "\ud83c\udfc6", R.drawable.emoji_e131);
        addPattern(emoticons, "\ud83d\udc7e", R.drawable.emoji_e12b);
        addPattern(emoticons, "\ud83c\udfaf", R.drawable.emoji_e130);
        addPattern(emoticons, "\ud83c\udc04", R.drawable.emoji_e12d);
        addPattern(emoticons, "\ud83c\udfac", R.drawable.emoji_e324);
        addPattern(emoticons, "\ud83d\udcdd", R.drawable.emoji_e301);
        addPattern(emoticons, "\ud83d\udcd3", R.drawable.emoji_e148);
        addPattern(emoticons, "\ud83c\udfa8", R.drawable.emoji_e502);
        addPattern(emoticons, "\ud83c\udfa4", R.drawable.emoji_e03c);
        addPattern(emoticons, "\ud83c\udfa7", R.drawable.emoji_e30a);
        addPattern(emoticons, "\ud83c\udfba", R.drawable.emoji_e042);
        addPattern(emoticons, "\ud83c\udfb7", R.drawable.emoji_e040);
        addPattern(emoticons, "\ud83c\udfb8", R.drawable.emoji_e041);
        addPattern(emoticons, "\u303d", R.drawable.emoji_e12c);
        addPattern(emoticons, "\ud83d\udc5e", R.drawable.emoji_e007);
        addPattern(emoticons, "\ud83d\udc61", R.drawable.emoji_e31a);
        addPattern(emoticons, "\ud83d\udc60", R.drawable.emoji_e13e);
        addPattern(emoticons, "\ud83d\udc62", R.drawable.emoji_e31b);
        addPattern(emoticons, "\ud83d\udc55", R.drawable.emoji_e006);
        addPattern(emoticons, "\ud83d\udc54", R.drawable.emoji_e302);
        addPattern(emoticons, "\ud83d\udc57", R.drawable.emoji_e319);
        addPattern(emoticons, "\ud83d\udc58", R.drawable.emoji_e321);
        addPattern(emoticons, "\ud83d\udc59", R.drawable.emoji_e322);
        addPattern(emoticons, "\ud83c\udf80", R.drawable.emoji_e314);
        addPattern(emoticons, "\ud83c\udfa9", R.drawable.emoji_e503);
        addPattern(emoticons, "\ud83d\udc51", R.drawable.emoji_e10e);
        addPattern(emoticons, "\ud83d\udc52", R.drawable.emoji_e318);
        addPattern(emoticons, "\ud83c\udf02", R.drawable.emoji_e43c);
        addPattern(emoticons, "\ud83d\udcbc", R.drawable.emoji_e11e);
        addPattern(emoticons, "\ud83d\udc5c", R.drawable.emoji_e323);
        addPattern(emoticons, "\ud83d\udc84", R.drawable.emoji_e31c);
        addPattern(emoticons, "\ud83d\udc8d", R.drawable.emoji_e034);
        addPattern(emoticons, "\ud83d\udc8e", R.drawable.emoji_e035);
        addPattern(emoticons, "\u2615", R.drawable.emoji_e045);
        addPattern(emoticons, "\ud83c\udf75", R.drawable.emoji_e338);
        addPattern(emoticons, "\ud83c\udf7a", R.drawable.emoji_e047);
        addPattern(emoticons, "\ud83c\udf7b", R.drawable.emoji_e30c);
        addPattern(emoticons, "\ud83c\udf78", R.drawable.emoji_e044);
        addPattern(emoticons, "\ud83c\udf76", R.drawable.emoji_e30b);
        addPattern(emoticons, "\ud83c\udf74", R.drawable.emoji_e043);
        addPattern(emoticons, "\ud83c\udf54", R.drawable.emoji_e120);
        addPattern(emoticons, "\ud83c\udf5f", R.drawable.emoji_e33b);
        addPattern(emoticons, "\ud83c\udf5d", R.drawable.emoji_e33f);
        addPattern(emoticons, "\ud83c\udf5b", R.drawable.emoji_e341);
        addPattern(emoticons, "\ud83c\udf71", R.drawable.emoji_e34c);
        addPattern(emoticons, "\ud83c\udf63", R.drawable.emoji_e344);
        addPattern(emoticons, "\ud83c\udf59", R.drawable.emoji_e342);
        addPattern(emoticons, "\ud83c\udf58", R.drawable.emoji_e33d);
        addPattern(emoticons, "\ud83c\udf5a", R.drawable.emoji_e33e);
        addPattern(emoticons, "\ud83c\udf5c", R.drawable.emoji_e340);
        addPattern(emoticons, "\ud83c\udf72", R.drawable.emoji_e34d);
        addPattern(emoticons, "\ud83c\udf5e", R.drawable.emoji_e339);
        addPattern(emoticons, "\ud83c\udf73", R.drawable.emoji_e147);
        addPattern(emoticons, "\ud83c\udf62", R.drawable.emoji_e343);
        addPattern(emoticons, "\ud83c\udf61", R.drawable.emoji_e33c);
        addPattern(emoticons, "\ud83c\udf66", R.drawable.emoji_e33a);
        addPattern(emoticons, "\ud83c\udf67", R.drawable.emoji_e43f);
        addPattern(emoticons, "\ud83c\udf82", R.drawable.emoji_e34b);
        addPattern(emoticons, "\ud83c\udf70", R.drawable.emoji_e046);
        addPattern(emoticons, "\ud83c\udf4e", R.drawable.emoji_e345);
        addPattern(emoticons, "\ud83c\udf4a", R.drawable.emoji_e346);
        addPattern(emoticons, "\ud83c\udf49", R.drawable.emoji_e348);
        addPattern(emoticons, "\ud83c\udf53", R.drawable.emoji_e347);
        addPattern(emoticons, "\ud83c\udf46", R.drawable.emoji_e34a);
        addPattern(emoticons, "\ud83c\udf45", R.drawable.emoji_e349);
        addPattern(emoticons, "\ud83c\udfe0", R.drawable.emoji_e036);
        addPattern(emoticons, "\ud83c\udfeb", R.drawable.emoji_e157);
        addPattern(emoticons, "\ud83c\udfe2", R.drawable.emoji_e038);
        addPattern(emoticons, "\ud83c\udfe3", R.drawable.emoji_e153);
        addPattern(emoticons, "\ud83c\udfe5", R.drawable.emoji_e155);
        addPattern(emoticons, "\ud83c\udfe6", R.drawable.emoji_e14d);
        addPattern(emoticons, "\ud83c\udfea", R.drawable.emoji_e156);
        addPattern(emoticons, "\ud83c\udfe9", R.drawable.emoji_e501);
        addPattern(emoticons, "\ud83c\udfe8", R.drawable.emoji_e158);
        addPattern(emoticons, "\ud83d\udc92", R.drawable.emoji_e43d);
        addPattern(emoticons, "\u26ea", R.drawable.emoji_e037);
        addPattern(emoticons, "\ud83c\udfec", R.drawable.emoji_e504);
        addPattern(emoticons, "\ud83c\udf07", R.drawable.emoji_e44a);
        addPattern(emoticons, "\ud83c\udf06", R.drawable.emoji_e146);
        addPattern(emoticons, "\ud83c\udfe7", R.drawable.emoji_e50a);
        addPattern(emoticons, "\ud83c\udfef", R.drawable.emoji_e505);
        addPattern(emoticons, "\ud83c\udff0", R.drawable.emoji_e506);
        addPattern(emoticons, "\u26fa", R.drawable.emoji_e122);
        addPattern(emoticons, "\ud83c\udfed", R.drawable.emoji_e508);
        addPattern(emoticons, "\ud83d\uddfc", R.drawable.emoji_e509);
        addPattern(emoticons, "\ud83d\uddfb", R.drawable.emoji_e03b);
        addPattern(emoticons, "\ud83c\udf04", R.drawable.emoji_e04d);
        addPattern(emoticons, "\ud83c\udf05", R.drawable.emoji_e449);
        addPattern(emoticons, "\ud83c\udf03", R.drawable.emoji_e44b);
        addPattern(emoticons, "\ud83d\uddfd", R.drawable.emoji_e51d);
        addPattern(emoticons, "\ud83c\udf08", R.drawable.emoji_e44c);
        addPattern(emoticons, "\ud83c\udfa1", R.drawable.emoji_e124);
        addPattern(emoticons, "\u26f2", R.drawable.emoji_e121);
        addPattern(emoticons, "\ud83c\udfa2", R.drawable.emoji_e433);
        addPattern(emoticons, "\ud83d\udea2", R.drawable.emoji_e202);
        addPattern(emoticons, "\ud83d\udea4", R.drawable.emoji_e135);
        addPattern(emoticons, "\u26f5", R.drawable.emoji_e01c);
        addPattern(emoticons, "\u2708", R.drawable.emoji_e01d);
        addPattern(emoticons, "\ud83d\ude80", R.drawable.emoji_e10d);
        addPattern(emoticons, "\ud83d\udeb2", R.drawable.emoji_e136);
        addPattern(emoticons, "\ud83d\ude99", R.drawable.emoji_e42e);
        addPattern(emoticons, "\ud83d\ude97", R.drawable.emoji_e01b);
        addPattern(emoticons, "\ud83d\ude95", R.drawable.emoji_e15a);
        addPattern(emoticons, "\ud83d\ude8c", R.drawable.emoji_e159);
        addPattern(emoticons, "\ud83d\ude93", R.drawable.emoji_e432);
        addPattern(emoticons, "\ud83d\ude92", R.drawable.emoji_e430);
        addPattern(emoticons, "\ud83d\ude91", R.drawable.emoji_e431);
        addPattern(emoticons, "\ud83d\ude9a", R.drawable.emoji_e42f);
        addPattern(emoticons, "\ud83d\ude83", R.drawable.emoji_e01e);
        addPattern(emoticons, "\ud83d\ude89", R.drawable.emoji_e039);
        addPattern(emoticons, "\ud83d\ude84", R.drawable.emoji_e435);
        addPattern(emoticons, "\ud83d\ude85", R.drawable.emoji_e01f);
        addPattern(emoticons, "\ud83c\udfab", R.drawable.emoji_e125);
        addPattern(emoticons, "\u26fd", R.drawable.emoji_e03a);
        addPattern(emoticons, "\ud83d\udea5", R.drawable.emoji_e14e);
        addPattern(emoticons, "\u26a0", R.drawable.emoji_e252);
        addPattern(emoticons, "\ud83d\udea7", R.drawable.emoji_e137);
        addPattern(emoticons, "\ud83d\udd30", R.drawable.emoji_e209);
        addPattern(emoticons, "\ud83c\udfe7", R.drawable.emoji_e154);
        addPattern(emoticons, "\ud83c\udfb0", R.drawable.emoji_e133);
        addPattern(emoticons, "\ud83d\ude8f", R.drawable.emoji_e150);
        addPattern(emoticons, "\ud83d\udc88", R.drawable.emoji_e320);
        addPattern(emoticons, "\u2668", R.drawable.emoji_e123);
        addPattern(emoticons, "\ud83c\udfc1", R.drawable.emoji_e132);
        addPattern(emoticons, "\ud83c\udf8c", R.drawable.emoji_e143);
        addPattern(emoticons, "\ud83c\uddef\ud83c\uddf5", R.drawable.emoji_e50b);
        addPattern(emoticons, "\ud83c\uddf0\ud83c\uddf7", R.drawable.emoji_e514);
        addPattern(emoticons, "\ud83c\udde8\ud83c\uddf3", R.drawable.emoji_e513);
        addPattern(emoticons, "\ud83c\uddfa\ud83c\uddf8", R.drawable.emoji_e50c);
        addPattern(emoticons, "\ud83c\uddeb\ud83c\uddf7", R.drawable.emoji_e50d);
        addPattern(emoticons, "\ud83c\uddea\ud83c\uddf8", R.drawable.emoji_e511);
        addPattern(emoticons, "\ud83c\uddee\ud83c\uddf9", R.drawable.emoji_e50f);
        addPattern(emoticons, "\ud83c\uddf7\ud83c\uddfa", R.drawable.emoji_e512);
        addPattern(emoticons, "\ud83c\uddec\ud83c\udde7", R.drawable.emoji_e510);
        addPattern(emoticons, "\ud83c\udde9\ud83c\uddea", R.drawable.emoji_e50e);
        addPattern(emoticons, "1\u20e3", R.drawable.emoji_e21c);
        addPattern(emoticons, "2\u20e3", R.drawable.emoji_e21d);
        addPattern(emoticons, "3\u20e3", R.drawable.emoji_e21e);
        addPattern(emoticons, "4\u20e3", R.drawable.emoji_e21f);
        addPattern(emoticons, "5\u20e3", R.drawable.emoji_e220);
        addPattern(emoticons, "6\u20e3", R.drawable.emoji_e221);
        addPattern(emoticons, "7\u20e3", R.drawable.emoji_e222);
        addPattern(emoticons, "8\u20e3", R.drawable.emoji_e223);
        addPattern(emoticons, "9\u20e3", R.drawable.emoji_e224);
        addPattern(emoticons, "0\u20e3", R.drawable.emoji_e225);
        addPattern(emoticons, "#\u20e3", R.drawable.emoji_e210);
        addPattern(emoticons, "\u2b06", R.drawable.emoji_e232);
        addPattern(emoticons, "\u2b07", R.drawable.emoji_e233);
        addPattern(emoticons, "\u2b05", R.drawable.emoji_e235);
        addPattern(emoticons, "\u27a1", R.drawable.emoji_e234);
        addPattern(emoticons, "\u2197", R.drawable.emoji_e236);
        addPattern(emoticons, "\u2196", R.drawable.emoji_e237);
        addPattern(emoticons, "\u2198", R.drawable.emoji_e238);
        addPattern(emoticons, "\u2199", R.drawable.emoji_e239);
        addPattern(emoticons, "\u25c0", R.drawable.emoji_e23b);
        addPattern(emoticons, "\u25b6", R.drawable.emoji_e23a);
        addPattern(emoticons, "\u23ea", R.drawable.emoji_e23d);
        addPattern(emoticons, "\u23e9", R.drawable.emoji_e23c);
        addPattern(emoticons, "\ud83c\udd97", R.drawable.emoji_e24d);
        addPattern(emoticons, "\ud83c\udd95", R.drawable.emoji_e212);
        addPattern(emoticons, "\ud83d\udd1d", R.drawable.emoji_e24c);
        addPattern(emoticons, "\ud83c\udd99", R.drawable.emoji_e213);
        addPattern(emoticons, "\ud83c\udd92", R.drawable.emoji_e214);
        addPattern(emoticons, "\ud83c\udfa6", R.drawable.emoji_e507);
        addPattern(emoticons, "\ud83c\ude01", R.drawable.emoji_e203);
        addPattern(emoticons, "\ud83d\udcf6", R.drawable.emoji_e20b);
        addPattern(emoticons, "\ud83c\ude35", R.drawable.emoji_e22a);
        addPattern(emoticons, "\ud83c\ude33", R.drawable.emoji_e22b);
        addPattern(emoticons, "\ud83c\ude50", R.drawable.emoji_e226);
        addPattern(emoticons, "\ud83c\ude39", R.drawable.emoji_e227);
        addPattern(emoticons, "\ud83c\ude2f", R.drawable.emoji_e22c);
        addPattern(emoticons, "\ud83c\ude3a", R.drawable.emoji_e22d);
        addPattern(emoticons, "\ud83c\ude36", R.drawable.emoji_e215);
        addPattern(emoticons, "\ud83c\ude1a", R.drawable.emoji_e216);
        addPattern(emoticons, "\ud83c\ude37", R.drawable.emoji_e217);
        addPattern(emoticons, "\ud83c\ude38", R.drawable.emoji_e218);
        addPattern(emoticons, "\ud83c\ude02", R.drawable.emoji_e228);
        addPattern(emoticons, "\ud83d\udebb", R.drawable.emoji_e151);
        addPattern(emoticons, "\ud83d\udeb9", R.drawable.emoji_e138);
        addPattern(emoticons, "\ud83d\udeba", R.drawable.emoji_e139);
        addPattern(emoticons, "\ud83d\udebc", R.drawable.emoji_e13a);
        addPattern(emoticons, "\ud83d\udead", R.drawable.emoji_e208);
        addPattern(emoticons, "\ud83c\udd7f", R.drawable.emoji_e14f);
        addPattern(emoticons, "\u267f", R.drawable.emoji_e20a);
        addPattern(emoticons, "\ud83d\ude87", R.drawable.emoji_e434);
        addPattern(emoticons, "\ud83d\udebe", R.drawable.emoji_e309);
        addPattern(emoticons, "\u3299", R.drawable.emoji_e315);
        addPattern(emoticons, "\u3297", R.drawable.emoji_e30d);
        addPattern(emoticons, "\ud83d\udd1e", R.drawable.emoji_e207);
        addPattern(emoticons, "\ud83c\udd94", R.drawable.emoji_e229);
        addPattern(emoticons, "\u2733", R.drawable.emoji_e206);
        addPattern(emoticons, "\u2734", R.drawable.emoji_e205);
        addPattern(emoticons, "\ud83d\udc9f", R.drawable.emoji_e204);
        addPattern(emoticons, "\ud83c\udd9a", R.drawable.emoji_e12e);
        addPattern(emoticons, "\ud83d\udcf3", R.drawable.emoji_e250);
        addPattern(emoticons, "\ud83d\udcf4", R.drawable.emoji_e251);
        addPattern(emoticons, "\ud83d\udcb9", R.drawable.emoji_e14a);
        addPattern(emoticons, "\ud83d\udcb1", R.drawable.emoji_e149);
        addPattern(emoticons, "\u2648", R.drawable.emoji_e23f);
        addPattern(emoticons, "\u2649", R.drawable.emoji_e240);
        addPattern(emoticons, "\u264a", R.drawable.emoji_e241);
        addPattern(emoticons, "\u264b", R.drawable.emoji_e242);
        addPattern(emoticons, "\u264c", R.drawable.emoji_e243);
        addPattern(emoticons, "\u264d", R.drawable.emoji_e244);
        addPattern(emoticons, "\u264e", R.drawable.emoji_e245);
        addPattern(emoticons, "\u264f", R.drawable.emoji_e246);
        addPattern(emoticons, "\u2650", R.drawable.emoji_e247);
        addPattern(emoticons, "\u2651", R.drawable.emoji_e248);
        addPattern(emoticons, "\u2652", R.drawable.emoji_e249);
        addPattern(emoticons, "\u2653", R.drawable.emoji_e24a);
        addPattern(emoticons, "\u26ce", R.drawable.emoji_e24b);
        addPattern(emoticons, "\ud83d\udd2f", R.drawable.emoji_e23e);
        addPattern(emoticons, "\ud83c\udd70", R.drawable.emoji_e532);
        addPattern(emoticons, "\ud83c\udd71", R.drawable.emoji_e533);
        addPattern(emoticons, "\ud83c\udd8e", R.drawable.emoji_e534);
        addPattern(emoticons, "\ud83c\udd7e", R.drawable.emoji_e535);
        addPattern(emoticons, "\ud83d\udd32", R.drawable.emoji_e21a);
        addPattern(emoticons, "\ud83d\udd34", R.drawable.emoji_e219);
        addPattern(emoticons, "\ud83d\udd33", R.drawable.emoji_e21b);
        addPattern(emoticons, "\ud83d\udd5b", R.drawable.emoji_e02f);
        addPattern(emoticons, "\ud83d\udd50", R.drawable.emoji_e024);
        addPattern(emoticons, "\ud83d\udd51", R.drawable.emoji_e025);
        addPattern(emoticons, "\ud83d\udd52", R.drawable.emoji_e026);
        addPattern(emoticons, "\ud83d\udd53", R.drawable.emoji_e027);
        addPattern(emoticons, "\ud83d\udd54", R.drawable.emoji_e028);
        addPattern(emoticons, "\ud83d\udd55", R.drawable.emoji_e029);
        addPattern(emoticons, "\ud83d\udd56", R.drawable.emoji_e02a);
        addPattern(emoticons, "\ud83d\udd57", R.drawable.emoji_e02b);
        addPattern(emoticons, "\ud83d\udd58", R.drawable.emoji_e02c);
        addPattern(emoticons, "\ud83d\udd59", R.drawable.emoji_e02d);
        addPattern(emoticons, "\ud83d\udd5a", R.drawable.emoji_e02e);
        addPattern(emoticons, "\u2b55", R.drawable.emoji_e332);
        addPattern(emoticons, "\u274c", R.drawable.emoji_e333);
        addPattern(emoticons, "\u00a9", R.drawable.emoji_e24e);
        addPattern(emoticons, "\u00ae", R.drawable.emoji_e24f);
        addPattern(emoticons, "\u2122", R.drawable.emoji_e537);
    }

    private static void addPattern(Map<Pattern, Integer> map, String smile,
                                   int resource) {
        map.put(Pattern.compile(Pattern.quote(smile)), resource);
    }

    public static boolean addSmiles(Context context, Spannable spannable) {

        boolean hasChanges = false;
        for (Entry<Pattern, Integer> entry : emoticons.entrySet()) {
            Matcher matcher = entry.getKey().matcher(spannable);
            while (matcher.find()) {
                boolean set = true;
                for (ImageSpan span : spannable.getSpans(matcher.start(),
                        matcher.end(), ImageSpan.class))
                    if (spannable.getSpanStart(span) >= matcher.start()
                            && spannable.getSpanEnd(span) <= matcher.end())
                        spannable.removeSpan(span);
                    else {
                        set = false;
                        break;
                    }
                if (set) {
                    hasChanges = true;
                    int scale = (int) TypedValue.applyDimension(TypedValue.COMPLEX_UNIT_DIP, 18, context.getResources().getDisplayMetrics());
                    final Bitmap bitmap = Bitmap.createScaledBitmap(drawableToBitmap(context.getResources().getDrawable(entry.getValue()), context), scale, scale, true);
                    spannable.setSpan(new ImageSpan(context, bitmap),
                            matcher.start(), matcher.end(),
                            Spannable.SPAN_EXCLUSIVE_EXCLUSIVE);
                }
            }
        }
        return hasChanges;
    }

    public static Spannable getSmiledText(Context context, CharSequence text) {
        Spannable spannable = spannableFactory.newSpannable(text);
        addSmiles(context, spannable);
        return spannable;
    }

    public static Bitmap drawableToBitmap(Drawable drawable, Context context) {
        if (drawable instanceof BitmapDrawable) {
            return ((BitmapDrawable) drawable).getBitmap();
        }

        try {
            int width = drawable.getIntrinsicWidth();
            width = width > 0 ? width : 1;
            int height = drawable.getIntrinsicHeight();
            height = height > 0 ? height : 1;

            Bitmap bitmap = Bitmap.createBitmap(width, height, Bitmap.Config.ARGB_8888);
            Canvas canvas = new Canvas(bitmap);
            drawable.setBounds(0, 0, canvas.getWidth(), canvas.getHeight());
            drawable.draw(canvas);
            return bitmap;
        } catch (Exception e) {
            return BitmapFactory.decodeResource(context.getResources(), R.drawable.default_avatar);
        }
    }
}
